name: APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer
    steps:
      - uses: actions/checkout@v4
      - run: |
          yes | buildozer android debug
      - uses: actions/upload-artifact@v4
        with:
          name: Voladopillo-APK
          path: bin/*.apk
